services:
  - type: web
    name: insertiq
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
